### ISSUE TITLE
Replace SASS with PostCSS

### ISSUE THREAD

**Issue by alvincrespo** [echobind/ember-headstart#21]
```
var config = {
  addons: [{
    name: 'ember-cli-postcss',
    why: 'adds compiling and filtering methods for working with postcss'
  }, {
    name: 'normalize.css'
    why: 'makes browsers render all elements more consistently and in line with modern standards.'
  }, {
    name: 'postcss',
    why: 'a tool for transforming styles with JS plugins'
  }, {
    name: 'postcss-cssnext',
    why: 'a PostCSS plugin that helps you to use the latest CSS syntax today'
  }, {
    name: 'postcss-import',
    why: 'consume local files, node modules or web_modules'
  }],
  bowerPackages: [
    ...
  ],
  installFiles: [
    ...
  ]
}

module.exports = config;

```

**Comment by cball** [comment]
👍

**Comment by alvincrespo** [comment]
So there is an interesting problem at the moment in the library, in that we assume that whatever package is defined in .headstart - it is an addon. However, there are cases where we want a package that isn't an addon (e.g. normalize.css, postcss, postcss-next, etc...)

I think there are a couple of workaround with this:

- Create a new key in .headstart called `packages`
  - The `packages` option would be an Array, similar to `addons` but would contain dependencies that are not addons
- For every object in `addons` we specify a `raw` key/value pair
  - `raw` would be used to define a package that is not an addon
- Automatically detect `ember-addon` packages
  - A prefix detection (e.g. `ember-`)  
    - This would not work for a libary like `liquid-fire`, so there would need to be library that holds these exceptions
  - Install the package defined in `addons` and then check if it is an `ember-addon`.

I personally believe the first option is the best since its a bit more explicit, but I do see that as being a bit confusing - especially since most engineers are used to just dumping their dependencies into package.json.

The last option would require some work, but is not impossible. The only unknown for me is how to check if an addon that is installed is an ember-addon? Also I'm curious if we need to install the dependency to figure out if it is an `ember-addon`? I would prefer to execute an npm command that would get some metadata that could be parsed out and then determine what route to take (install addon or install raw package).

Thoughts?

**Comment by cball** [comment]
@alvincrespo I agree with going the explicit route here. Later we can update to be smarter like what you suggested. I imagine npm API returns this metadata somehow: https://github.com/echobind/ember-headstart/blob/master/package.json#L46

**Comment by alvincrespo** [comment]
Cool - Ill go down the simple route for now and we can revisit it if/when it becomes a pain point.
